Sprint 12
IuriiKarpunov/ImageFeed pull request #7
Opened 2023-09-07 15:34 UTC by IuriiKarpunov

2023-09-07 19:08 UTC, protos17 requested changes

2023-09-07 19:08 UTC, protos17 commented on ImageFeed/SingleImageViewController/SingleImageViewController.swift
> +                self.rescaleAndCenterImageInScrollView(image: imageResult.image)
Нужно еще эту картинку присвоить для image, чтобы можно было поделиться:

self.image = imageResult.image

2023-09-07 19:08 UTC, protos17 commented on ImageFeed/SingleImageViewController/SingleImageViewController.swift
>      var image: UIImage! {
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, когда они используются только внутри области объявления.

2023-09-07 19:08 UTC, protos17 commented on ImageFeed/Helpers/Date+Extensions.swift
> -    var dateString: String { dateFormatter.string(from: self) }
Рекомендую форматтер перенести в сам extension:

    private var dateFormatter: DateFormatter {
        let formatter = DateFormatter()
        formatter.dateStyle = .long
        formatter.timeStyle = .none
        return formatter
    }

2023-09-07 19:08 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        let configuringCellStatus = imagesListCell.configCell(photoURL: photos[indexPath.row].thumbImageURL, with: indexPath)
Чтобы состояние лайка корректно отображалось, здесь необходимо присваивать состояние лайка необходимым ячейкам:

imagesListCell.setIsLiked(isLiked: photos[indexPath.row].isLiked)

2023-09-07 19:08 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        return photos.count
При возвращении значения одной строкой можно не писать return

2023-09-07 19:08 UTC, protos17 commented on ImageFeed/AppDelegate.swift
> +            return true
Рекомендую выровнять

2023-09-07 19:08 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListCell.swift
> +        ) { result in
Сильная ссылка, необходимо добавить [weak self]

2023-09-07 19:08 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListCell.swift
> +        let likeImage = isLiked ? UIImage(named: "like_button_on") : UIImage(named: "like_button_off")
Можно писать так:

let likeImage = UIImage(named: isLiked ? "like_button_on" : "like_button_off")

2023-09-07 19:08 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
>  class ImagesListViewController: UIViewController {
Классы без наследования рекомендую указывать как final

2023-09-07 19:08 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
>              let indexPath = sender as! IndexPath
Не рекомендую использовать force cast, лучше реализовать проверку через guard let

2023-09-07 19:08 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            isLike: photo.isLiked) { result in
Сильная ссылка, необходимо добавить [weak self]

2023-09-07 19:08 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +                    UIBlockingProgressHUD.dismiss()
Чтобы не дублировать UIBlockingProgressHUD.dismiss() (принцип DRY) - рекомендую вынести их в общую область видимости switcha

2023-09-07 19:08 UTC, protos17 commented on ImageFeed/Models/AlertModel.swift
> +    let buttonText2: String
Рекомендую не задавать имена константам и переменным наподобие 1, 2, 3 и т.д. Лучше назвать их, например, yesButtonText, noButtonText

2023-09-07 19:08 UTC, protos17 commented on ImageFeed/Services/ImagesListService.swift
> +    static let DidChangeNotification = Notification.Name(rawValue: "ImagesListServiceDidChange")
1) Константы принято писать с маленькой буквы.

2) Можно написать так и использовать ее в NotificationCenter через точку:

extension Notification.Name {
    static let didChangeNotification = Notification.Name("ImagesListServiceDidChange")
}

2023-09-07 19:08 UTC, protos17 commented on ImageFeed/Services/ImagesListService.swift
> +                            )
Рекомендую преобразование из модели в другую модель делать в отдельном методе. Иногда, если таких преобразований много, принято писать маппер, например, структуру, в которой находятся такие методы, которые данные с бэка маппят в данные для наших моделей приложения

2023-09-07 19:08 UTC, protos17 commented on ImageFeed/Services/ImagesListService.swift
> +                            isLiked: likedByUser
Можно isLiked сделать как переменную var и менять только ее

2023-09-07 20:04 UTC, IuriiKarpunov commented on ImageFeed/ImagesList/ImagesListViewController.swift
>  class ImagesListViewController: UIViewController {
+

2023-09-07 20:04 UTC, IuriiKarpunov commented on ImageFeed/SingleImageViewController/SingleImageViewController.swift
> +                self.rescaleAndCenterImageInScrollView(image: imageResult.image)
+

2023-09-07 20:12 UTC, IuriiKarpunov commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        let configuringCellStatus = imagesListCell.configCell(photoURL: photos[indexPath.row].thumbImageURL, with: indexPath)
+

2023-09-07 20:14 UTC, IuriiKarpunov commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        return photos.count
+

2023-09-07 20:15 UTC, IuriiKarpunov commented on ImageFeed/AppDelegate.swift
> +            return true
+

2023-09-07 20:16 UTC, IuriiKarpunov commented on ImageFeed/SingleImageViewController/SingleImageViewController.swift
>      var image: UIImage! {
+

2023-09-07 20:18 UTC, IuriiKarpunov commented on ImageFeed/ImagesList/ImagesListCell.swift
> +        ) { result in
+

2023-09-07 20:20 UTC, IuriiKarpunov commented on ImageFeed/ImagesList/ImagesListCell.swift
> +        let likeImage = isLiked ? UIImage(named: "like_button_on") : UIImage(named: "like_button_off")
+

2023-09-07 20:28 UTC, IuriiKarpunov commented on ImageFeed/ImagesList/ImagesListViewController.swift
>              let indexPath = sender as! IndexPath
+

2023-09-07 20:28 UTC, IuriiKarpunov commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            isLike: photo.isLiked) { result in
+

2023-09-07 20:35 UTC, IuriiKarpunov commented on ImageFeed/Models/AlertModel.swift
> +    let buttonText2: String
+

2023-09-07 20:39 UTC, IuriiKarpunov commented on ImageFeed/Services/ImagesListService.swift
> +    static let DidChangeNotification = Notification.Name(rawValue: "ImagesListServiceDidChange")
+

2023-09-07 21:04 UTC, IuriiKarpunov commented on ImageFeed/Services/ImagesListService.swift
> +                            )
+

2023-09-08 14:35 UTC, protos17 approved these changes

2023-09-08 14:35 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            }
Можно сразу сделать присваивание и проверку:

guard let viewController = segue.destination as? SingleImageViewController,
            let indexPath = sender as? IndexPath else { 
return 
}

2023-09-08 17:48 UTC, IuriiKarpunov commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            }
+

2023-09-08 18:08 UTC, merged